http:
  '100': Continue
  '101': Switching Protocol
  '102': Processing
  '103': Early Hints
  '200': OK
  '201': Created
  '202': Accepted
  '203': No Content
  '204': No Content
  '205': Reset Content
  '206': Partial Content (RFC 7233)
  '207': Multi-Status
  '208': Multi-Status
  '226': IM Used ( Delta encoding)
  '300': Multiple Choices
  '301': Moved Permanently
  '302': Found
  '303': See Other (en-US)
  '304': Not Modified
  '305': Use Proxy
  '306': Unused
  '307': Temporary Redirect (since /11)
  '308': Permanent Redirect (RFC 7538)
  '400': Bad Request
  '401': Unauthorized (RFC 7235)
  '402': Payment Required
  '403': Forbidden
  '404': Resource Not Found
  '405': Method Not Allowed
  '406': Not Acceptable
  '407': Proxy Authentication Required (RFC 7235)
  '408': Request Timeout
  '409': Conflict
  '410': Gone (en-US)
  '411': Length Required
  '412': Precondition Failed (RFC 7232)
  '413': Payload Too Large (RFC 7231)
  '414': URI Too Long (RFC 7231)
  '415': Unsupported Media Type (RFC 7231)
  '417': Expectation Failed
  '416': Requested Range Not Satisfiable
  '418': I'm a teapot (RFC 2324, RFC 7168)
  '421': Misdirected Request (RFC 7540)
  '422': Unprocessable Entity
  '423': Locked (WebDAV; RFC 4918)
  '424': Failed Dependency
  '426': Upgrade Required (en-US)
  '428': Precondition Required (en-US)
  '429': Too Many Requests (RFC 6585)
  '431': Request Header Fields Too Large (RFC 6585)
  '451': Unavailable For Legal Reasons (RFC 7725)
  '500': Internal Server Error
  '501': Not Implemented
  '502': Bad Gateway
  '503': Service Unavailable
  '504': Gateway Timeout
  '505': Version Not Supported
  '506': Variant Also Negotiates (en-US)
  '507': Insufficient Storage (WebDAV; RFC 4918)
  '508': Loop Detected (WebDAV; RFC 5842)
  '510': Not Extended (RFC 2774)
  '511': Network Authentication Required (RFC 6585)
leap:
  '900': Received negative value from request. {}
  '901': Not supported option. {}             {}