/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.chaostocosmos.leap.http;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.StringReader;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.net.InetAddress;
import java.net.UnknownHostException;

import org.junit.jupiter.api.Test;

class UtilBoxTest {

    @Test
    public void testSomting() throws UnknownHostException {
        String host = "localhost";
        InetAddress ia = InetAddress.getByName(host);
        System.out.println(ia.getHostName());
    }

    @Test
    public void testInstantiate() throws NoSuchMethodException, SecurityException, ClassNotFoundException, InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException {
        ClassLoader classLoader = ClassLoader.getSystemClassLoader();
        String qualifiedClassName = "com.nhn.was.servlet.TimeServletImpl";
        Class<?> clazz = classLoader.loadClass(qualifiedClassName);
        Constructor<?>[] constructors = clazz.getConstructors();
        Constructor<?> constructor = constructors[0];
        constructor.setAccessible(true);
        constructor.newInstance();
        System.out.println("ok");
    }

    @Test
    public void testIO() throws IOException {
        String str = "a\r\nb\r\n\r\nc";
        BufferedReader reader = new BufferedReader(new StringReader(str));
        for(String line; (line=reader.readLine()) != null; ) {
            System.out.println(line.length());
        }
    }

    public static void main(String[] args) {
        System.out.println((long)Integer.MAX_VALUE * 100);
    }

}
